Added Build badge for travis CI to README
anitab-org/bridge-in-tech-web pull request #111
Opened 2020-09-23 05:34 UTC by AltCtrlDel1999

### Description

Added Build status badge into the README file

Fixes #ISSUE
#108 
### Type of Change:

- Documentation

### How Has This Been Tested?
Checked Manually

2020-09-24 17:50 UTC, AltCtrlDel1999 commented
@mtreacy002 Please review this PR

2020-09-24 23:50 UTC, mtreacy002 requested changes
@AltCtrlDel1999 , please check my feedback below.

2020-09-24 23:50 UTC, mtreacy002 commented on src/config.js
> +//export const BASE_API = process.env.REACT_APP_BASE_API ?  process.env.REACT_APP_BASE_API : "bridgeintech-bit-heroku-psql.herokuapp.com"
@AltCtrlDel1999 , please remove this commented line.

2020-09-25 05:19 UTC, AltCtrlDel1999 commented
@mtreacy002 Done with changes.

2020-09-27 22:31 UTC, mtreacy002 requested changes
@AltCtrlDel1999 . There is a conflict caused by the recent merge to upstream develop. Can you please integrate this into your code by pull --rebase from upstream develop? Thanks

2020-09-29 05:01 UTC, AltCtrlDel1999 commented
@mtreacy002 Done

2020-09-29 08:29 UTC, mtreacy002 approved these changes
LGTM 🎉🎉 . Thank you for your contribution, @AltCtrlDel1999

2020-09-29 08:29 UTC, merged