Doc: Add information to README  that Heroku servers are unavailable
anitab-org/bridge-in-tech-web pull request #114
Opened 2020-09-29 00:56 UTC by mtreacy002

### Description
Add information that Heroku serverrs are currently unavailable due to [free dynos limitation](https://medium.com/anitab-org-open-source/why-you-cant-use-heroku-free-dynos-in-multiple-servers-dependent-application-fa1cdd9e9e07?source=friends_link&sk=281bb76050f052c03c6772e9be275f67)

Fixes #113 

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
NA

### How Has This Been Tested?

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2020-10-03 13:36 UTC, rpattath requested changes

2020-10-03 13:36 UTC, rpattath commented on README.md
> +* The BIT Heroku backend server will only carries the latest code that have been approved and merged to the develop branch. This means, if you are working on a PR or testing an open PR, this **Option
Please fix the typo "will only carries"

2020-10-03 23:01 UTC, mtreacy002 commented on README.md
> +* The BIT Heroku backend server will only carries the latest code that have been approved and merged to the develop branch. This means, if you are working on a PR or testing an open PR, this **Option
Done 😉.

2020-10-04 10:05 UTC, isabelcosta approved these changes
Great update!

2020-10-04 13:37 UTC, gaurivn approved these changes
Good, nicely written

2020-10-12 23:32 UTC, merged