Nav style done
anitab-org/bridge-in-tech-web pull request #124
Opened 2020-10-21 05:13 UTC by prathmeshkhandelwal1

### Description

NavBar design Done

Fixes #117 

### Type of Change:

- Code
- Quality Assurance
- User Interface

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### Screeshot of change

![Screenshot (140)](https://user-images.githubusercontent.com/56167998/96676139-4640d280-138a-11eb-8dc8-c747134d3ad1.png)

2020-10-21 05:15 UTC, prathmeshkhandelwal1 commented
@mtreacy002  Sorry for the late PR. Actually I was out of town

2020-10-23 21:14 UTC, mtreacy002 commented
That's ok. Thanks, @prathmeshkhandelwal1 for the update. I'll review it today.

2020-10-24 11:31 UTC, mtreacy002 requested changes
@prathmeshkhandelwal1 , I've tested the navbar and overall it looks good. Although, I am wondering if it's possible for you to fix the positioning of Register/Login or Logout/Welcome back <user>! section when user click main navbar with submenus (note that this bug exist on the original issue, but since the section are separate to the rest of Navbar (left vs right) and not together as the new change, the bug is not as obvious):

**Before the change:**
* when `Home` tab is clicked:
<img width="1672" alt="Screen Shot 2020-10-24 at 10 16 02 pm" src="https://user-images.githubusercontent.com/29667122/97080594-38b87080-1648-11eb-9a59-93af92e12d79.png">

* when `My Space` tab is clicked:
<img width="1679" alt="Screen Shot 2020-10-24 at 10 16 14 pm" src="https://user-images.githubusercontent.com/29667122/97080608-5685d580-1648-11eb-8cad-438a3a17605a.png">

**After the change**
* when `Home` tab is clicked:
<img width="1675" alt="Screen Shot 2020-10-24 at 9 58 45 pm" src="https://user-images.githubusercontent.com/29667122/97080626-76b59480-1648-11eb-9cdd-b3734a7895fd.png">

* when `My Space` tab is clicked:
<img width="1677" alt="Screen Shot 2020-10-24 at 10 00 26 pm" src="https://user-images.githubusercontent.com/29667122/97080631-859c4700-1648-11eb-8aad-7eb42411c415.png">

Let me know if you have a question 😉.

2020-10-25 06:32 UTC, prathmeshkhandelwal1 commented
> @prathmeshkhandelwal1 , I've tested the navbar and overall it looks good. Although, I am wondering if it's possible for you to fix the positioning of Register/Login or Logout/Welcome back ! section when user click main navbar with submenus (note that this bug exist on the original issue, but since the section are separate to the rest of Navbar (left vs right) and not together as the new change, the bug is not as obvious):
> 
> **Before the change:**
> 
> * when `Home` tab is clicked:
> 
> <img alt="Screen Shot 2020-10-24 at 10 16 02 pm" width="1672" src="https://user-images.githubusercontent.com/29667122/97080594-38b87080-1648-11eb-9a59-93af92e12d79.png">
> 
> * when `My Space` tab is clicked:
> 
> <img alt="Screen Shot 2020-10-24 at 10 16 14 pm" width="1679" src="https://user-images.githubusercontent.com/29667122/97080608-5685d580-1648-11eb-8cad-438a3a17605a.png">
> 
> **After the change**
> 
> * when `Home` tab is clicked:
> 
> <img alt="Screen Shot 2020-10-24 at 9 58 45 pm" width="1675" src="https://user-images.githubusercontent.com/29667122/97080626-76b59480-1648-11eb-9cdd-b3734a7895fd.png">
> 
> * when `My Space` tab is clicked:
> 
> <img alt="Screen Shot 2020-10-24 at 10 00 26 pm" width="1677" src="https://user-images.githubusercontent.com/29667122/97080631-859c4700-1648-11eb-8aad-7eb42411c415.png">
> 
> Let me know if you have a question 😉.

okk i will try to fix it..as here `accordian` is used from react/bootstrap bcoz of that i was unable to do it. i will try once again maybe i can do something.

2020-10-26 14:07 UTC, prathmeshkhandelwal1 commented
@mtreacy002 I tried many solns but its now working can you help me with this?

2020-10-26 14:12 UTC, prathmeshkhandelwal1 commented
@mtreacy002 Can you review it plz?

2020-10-27 04:12 UTC, mtreacy002 approved these changes
This PR is tested locally on MacOS Cataline 10.15.7 with Google Chrome browser.
The followings are the test results:
* expected behaviour: Main Nav shows layout as per [proposal design](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1) in Figma file
* actual behaviour: as expected

**Additional info:**
The bug which shows the Register/Login and Logout/Welome <user>! Navs drop when `Home` and `My Space` tabs were clicked on initial PR has also been removed.
On non-logged in user:
<img width="1636" alt="Screen Shot 2020-10-27 at 2 56 52 pm" src="https://user-images.githubusercontent.com/29667122/97256212-8c080a00-1866-11eb-8327-b7075842ae7c.png">
<img width="1660" alt="Screen Shot 2020-10-27 at 2 57 05 pm" src="https://user-images.githubusercontent.com/29667122/97256223-91655480-1866-11eb-938c-2b075dfbbae7.png">

On logged-in user:
<img width="1673" alt="Screen Shot 2020-10-27 at 2 57 41 pm" src="https://user-images.githubusercontent.com/29667122/97256249-ae018c80-1866-11eb-89d4-60f2d9677333.png">
<img width="1675" alt="Screen Shot 2020-10-27 at 2 57 25 pm" src="https://user-images.githubusercontent.com/29667122/97256259-b2c64080-1866-11eb-808b-67e261aa64b5.png">

Well done, @prathmeshkhandelwal1  and thank you for your ocntribution 🎉🎉🎉

2020-10-27 04:12 UTC, mtreacy002 commented on debug.log
> +[1016/123751.432:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Can you please add this file on .gitignore so it won't be included in the code to be merged?

2020-10-27 04:15 UTC, mtreacy002 requested changes
Sorry, I'll reapprove after you remove the debug.log

2020-10-27 04:34 UTC, prathmeshkhandelwal1 commented
> Sorry, I'll reapprove after you remove the debug.log

Sure

2020-10-27 06:41 UTC, mtreacy002 approved these changes
Thanks, @prathmeshkhandelwal1 for accommodating the change requested. It looks good now 👍

2020-10-27 06:45 UTC, merged

2020-10-27 08:11 UTC, prathmeshkhandelwal1 commented
> Thanks, @prathmeshkhandelwal1 for accommodating the change requested. It looks good now 👍

😉