Feat: Add code of conduct, terms and privacy policy modal
anitab-org/bridge-in-tech-web pull request #179
Opened 2021-02-23 18:10 UTC by Rahulm2310

### Description

Add Code of Conduct, Terms and Privacy Policy modal popup on the register page.

Fixes #176 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

![bit-terms-modal-2](https://user-images.githubusercontent.com/54268438/108887535-67634980-7630-11eb-959f-76f815bb84f5.gif)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2021-02-23 18:11 UTC, Rahulm2310 commented
@mtreacy002 Please review this PR. Thanks 🙂

2021-02-24 10:53 UTC, mtreacy002 requested changes
@Rahulm2310 , can you please resolve the conflict first? I'll give my review once you've done this. Thanks

2021-02-24 18:22 UTC, Rahulm2310 commented
@mtreacy002 Done 🙂. Please review it now

2021-02-25 03:16 UTC, mtreacy002 commented
> @mtreacy002 Done 🙂. Please review it now

will do that today 😉.

2021-02-27 11:14 UTC, mtreacy002 reviewed
@Rahulm2310 , I think it looks good now. Thank you for the fix, I just need to confirm with @anitab-org/admins that this code of conduct, terms and privacy policy can be used in BridgeInTech project. Also, can you please provide the links to the pages where you find the contents in your reply to this comment? Thanks beforehand.

2021-02-27 16:41 UTC, Rahulm2310 commented
@mtreacy002 Sure. Here are the links to the pages 
1. [https://anitab.org/privacy-policy/](https://anitab.org/privacy-policy/)
2. [https://anitab.org/terms-of-use/](https://anitab.org/terms-of-use/)
3. [https://ghc.anitab.org/code-of-conduct/](https://ghc.anitab.org/code-of-conduct/)

Also, I think Mentorship System is also using the same links for the project.

2021-02-28 07:58 UTC, mtreacy002 commented
> @mtreacy002 Sure. Here are the links to the pages
> 
> 1. https://anitab.org/privacy-policy/
> 2. https://anitab.org/terms-of-use/
> 3. https://ghc.anitab.org/code-of-conduct/
> 
> Also, I think Mentorship System is also using the same links for the project.

thanks for the links, @Rahulm2310 . In tonight's open session we could ask confirmation from @isabelcosta as she hopefully will join us there 😉.

2021-02-28 13:27 UTC, mtreacy002 requested changes
@Rahulm2310 , please check my feedback below.

2021-02-28 13:27 UTC, mtreacy002 commented on src/register/TermsAndPrivacyPolicyModal.jsx
> +          <Tab eventKey="code-of-conduct" title="Code of Conduct">
@Rahulm2310 , please replace the content for the Code of Conduct to [this one](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md) from the Code of Conduct under anitab-org/documentation. The one you provide here is specific to GHC code of conduct only.

2021-02-28 17:47 UTC, Rahulm2310 commented
@mtreacy002 Applied suggested changes. Please have a look now. 🙂

2021-03-01 01:21 UTC, mtreacy002 requested changes
@Rahulm2310 , thank you for the fix. Can you please squash your commits into one? I will write the test report and approve after that.

2021-03-01 19:03 UTC, Rahulm2310 commented
@mtreacy002 Is it okay now ?

2021-03-01 21:03 UTC, mtreacy002 commented
> @mtreacy002 Is it okay now ?

@Rahulm2310 , how come it's still showing 2 commits 😁?

2021-03-02 04:39 UTC, Rahulm2310 commented
@mtreacy002 Actually, I squashed my commits and pushed my changes but there were conflicts which I then resolved using GitHub GUI.

2021-03-02 05:05 UTC, mtreacy002 commented
@Rahulm2310 , it is good to develop the habit to "pull --rebase" from upstream and resolve any conflicts before you squash your commits and push the changes again to avoid being in this situation. But that's ok, with AnitaB.Org Open Source, maintainer actually can squash the commits at our end 😁. I just think  it's good to learn the efficient workflow as other Open Source organizations might have different GitHub settings/rules and expects contributors to squash the commits from their end 😁. 
Would you like to me to squash the commits at my end for now or do you want to squash the commits again at your end?

2021-03-02 06:17 UTC, Rahulm2310 commented
@mtreacy002 learn a lot here 😊. Thanks, will try it at my end 👍

2021-03-02 19:52 UTC, Rahulm2310 commented
@mtreacy002 Please review it now. 🙂

2021-03-03 20:13 UTC, codesankalp reviewed
@Rahulm2310 @mtreacy002 
I have a suggestion.
Instead of adding all the terms and privacy policy in the form of jsx in `TermsAndPrivacyPolicyModal.jsx` why don't we use a markdown parser to parse these markdowns from their actual source when loading the modal.
If we will use this then whenever their is a change in code of conduct, terms, and privacy policy then it will automatically change on the webpage instead of manually changing it again and again.

2021-03-03 22:29 UTC, mtreacy002 commented
That sounds like a great idea, @codesankalp. @Rahulm2310 will you be able to accommodate this?

2021-03-04 18:22 UTC, Rahulm2310 commented
@codesankalp seems a nice idea but what do you mean by using a markdown parser. Did you mean scraping ?

2021-03-04 18:28 UTC, codesankalp commented
@Rahulm2310 Just fetch the content from GitHub Readme or markdown files.
Example:
Like fetch the content from this README URL (https://raw.githubusercontent.com/anitab-org/bridge-in-tech-web/develop/README.md) and then convert it into HTML by using markdown parser (https://www.npmjs.com/package/markdown-it).
We can't say it scraping because scraping is different, this is just fetching and parsing.

2021-03-04 18:35 UTC, Rahulm2310 commented
@codesankalp Only the [Code of Conduct](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md) is a markdown file. [Terms](https://anitab.org/terms-of-use/) & [Privacy Policy](https://anitab.org/privacy-policy/) are present on AnitaB.org's official website.

2021-03-04 21:13 UTC, mtreacy002 commented
@codesankalp, what @Rahulm2310 says make sense. I've [asked admin](https://anitab-org.zulipchat.com/#narrow/stream/216326-documentation/topic/anitab-org.2Fdocumentation/near/228503958) if we can open an issue to create .md files for these Terms of Use and Privacy Policy. We can refactor this code later once that issue is solved. I'll approve this issue now

2021-03-04 21:25 UTC, mtreacy002 approved these changes
Well done, @Rahulm2310 for adding this feature. Below is the test result:
1. Code review: done
2. All possible responses were tested as below:
    * Test PR 179 - add code of conduct, terms of use and privacy policy modal
    Expected behaviour: When user click on the link to Code of Conduct, Terms and Privacy Policy, a modal pop-up should open with content of the 3 policies above.
    Actual behaviour: As expected

![ezgif com-gif-maker (34)](https://user-images.githubusercontent.com/29667122/110032273-0eac5300-7d8c-11eb-99ab-7e9aafb23964.gif)

3. Environment:
    OS: macOS Catalina v10.15.7
    Browser: Chrome v88.0.4324.192

Thank you again, @Rahulm2310 for contributing to the project 🎉🎉🎉

2021-03-04 21:26 UTC, merged