docs: add link to Bridge In Tech zulip stream in CONTRIBUTING.md
anitab-org/bridge-in-tech-web pull request #219
Opened 2021-04-01 11:28 UTC by battuAshita

### Description

Fixes #204

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

2021-04-01 13:53 UTC, devkapilbansal submitted a review, later dismissed
LGTM :+1: 
Thanks @battuAshita for this

2021-04-01 14:01 UTC, codesankalp requested changes
@battuAshita Thanks for your contribution :rocket: 
It will be ready to merge if you will make the suggested changes.
The changes are small but important as it resembles more with other repos `CONTRIBUTING.md`

2021-04-01 14:01 UTC, codesankalp commented on .github/CONTRIBUTING.md
> +* You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). Each active repo has its own stream to direct questions to (for example #powerup or #portal). You can find the
```suggestion
* You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). Each active repo has its own stream to direct questions to (for example #powerup or #portal). Bridge in Tech stream is [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech).
```

2021-04-01 14:15 UTC, battuAshita commented on .github/CONTRIBUTING.md
> +* You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). Each active repo has its own stream to direct questions to (for example #powerup or #portal). You can find the
Will do these changes :)

2021-04-01 14:45 UTC, codesankalp approved these changes
LGTM :tada: , Thanks again @battuAshita for your contribution.

2021-04-01 14:52 UTC, Amulya-coder approved these changes
LGTM @battuAshita Thanks for your contribution 🎉

2021-04-02 16:00 UTC, isabelcosta approved these changes
Great work @battuAshita 🎉

2021-04-02 22:23 UTC, merged