Feat: View/Create and Update Organization Profile
anitab-org/bridge-in-tech-web pull request #69
Opened 2020-08-17 05:57 UTC by mtreacy002

### Description
Added View Organization Profile Functionality

Fixes #50, #51 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- login as user who has an additional info with is_organization_rep value True but has not created an organization. 

* on View organization profile
- go to MyOrganization > Profile. On successful GET /organization see response below
<img width="950" alt="Screen Shot 2020-08-17 at 3 29 57 pm" src="https://user-images.githubusercontent.com/29667122/90361336-47f7cc80-e0a1-11ea-8c71-61874744ff11.png">

* On Create organization profile
- Add details for the organization and click `Save`. On successful create, see response below.
<img width="968" alt="Screen Shot 2020-08-17 at 3 41 03 pm" src="https://user-images.githubusercontent.com/29667122/90361479-ac1a9080-e0a1-11ea-9add-3c8904bc5f6f.png">

To check if the data is saved to database, move away from the MyOrganization Profile page (click on any other page) and comeback. See response below:
<img width="946" alt="Screen Shot 2020-08-17 at 3 41 19 pm" src="https://user-images.githubusercontent.com/29667122/90361594-f69c0d00-e0a1-11ea-84ad-342a0e40a8a5.png">
 
* On Update organization profile:
- change the details on the organization page and click `Save`. On successful update, see response below:
<img width="965" alt="Screen Shot 2020-08-17 at 3 41 34 pm" src="https://user-images.githubusercontent.com/29667122/90361671-2519e800-e0a2-11ea-8f6a-e1d98644e7a5.png">

to check if the data is updated, move away from thee MyOrganization Profile page (click on any other page) and comeback. See response below:
<img width="933" alt="Screen Shot 2020-08-17 at 3 41 48 pm" src="https://user-images.githubusercontent.com/29667122/90361729-4a0e5b00-e0a2-11ea-8523-b12fc3e4bf51.png">

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-08-17 06:07 UTC, mtreacy002 commented
Update @anitab-org/bridgeintech-maintainers . I've completed View/Create/Update Organization profile on this one PR. Since we only have one week to go to complete the project features, I'll move on to the next functionalities first which are the View organizations and view other organization profile (where user has selected the organization name from the Organizations list). 
@isabelcosta  and @meenakshi-dhanani , is it ok if for now I do the remaining testing on UI (starting from View Additional Info onwards) after I complete the remaining deliverables (still have Programs and Send application Form to a Mentoring Program backend and frontend after Organizations UI completed). If all goes well, this week I'll complete all deliverables, theen I can finish off the testing UI next week whilee wrapping up. Let me know what you think.

2020-08-18 00:46 UTC, mtreacy002 commented
@meenakshi-dhanani and @ramitsawhney27 , I want to point out that atm I didn't show the `join date` info of the organization. This is because I'm not sure where to put the logic of converting the date to human readable format. If we follow the enum logic which is kept at backend, I need to refactor backend to add that logic (converting date for GET and PUT API endpoints). However, I remembered that we had that discussion on the initial stage of development that dates format on backend is to be kept in the UNIX as to keep it as close to the machine language. Can you both please share your opinion on this, whether to put the conversion logic on the frontend or backend? Thanks.

2020-08-18 18:57 UTC, meenakshi-dhanani commented
> @meenakshi-dhanani and @ramitsawhney27 , I want to point out that atm I didn't show the `join date` info of the organization. This is because I'm not sure where to put the logic of converting the date to human readable format. If we follow the enum logic which is kept at backend, I need to refactor backend to add that logic (converting date for GET and PUT API endpoints). However, I remembered that we had that discussion on the initial stage of development that dates format on backend is to be kept in the UNIX as to keep it as close to the machine language. Can you both please share your opinion on this, whether to put the conversion logic on the frontend or backend? Thanks.

Getting back to the earlier discussion, it wasn't just about keeping the detail in the backend. One thing we agreed on was keeping it in one place. Since all of the timezone information was all on the backend, we chose to not do a larger change and thus stuck to having it in the backend. If it's not your core business logic though, and if it's presentation logic feel free to do things on the frontend. 

In this case I don't have a strong reason for why the calculation needs to be in the frontend, though I usually have seen APIs returning readable dates from the backend, eg. 2020-01-06T20:22:05.000Z. While using the API, just as an API, it's far more convenient to have in human readable format. I'd prefer backend.

2020-08-19 11:34 UTC, mtreacy002 commented
> > @meenakshi-dhanani and @ramitsawhney27 , I want to point out that atm I didn't show the `join date` info of the organization. This is because I'm not sure where to put the logic of converting the date to human readable format. If we follow the enum logic which is kept at backend, I need to refactor backend to add that logic (converting date for GET and PUT API endpoints). However, I remembered that we had that discussion on the initial stage of development that dates format on backend is to be kept in the UNIX as to keep it as close to the machine language. Can you both please share your opinion on this, whether to put the conversion logic on the frontend or backend? Thanks.
> 
> Getting back to the earlier discussion, it wasn't just about keeping the detail in the backend. One thing we agreed on was keeping it in one place. Since all of the timezone information was all on the backend, we chose to not do a larger change and thus stuck to having it in the backend. If it's not your core business logic though, and if it's presentation logic feel free to do things on the frontend.
> 
> In this case I don't have a strong reason for why the calculation needs to be in the frontend, though I usually have seen APIs returning readable dates from the backend, eg. 2020-01-06T20:22:05.000Z. While using the API, just as an API, it's far more convenient to have in human readable format. I'd prefer backend.

Thanks, @meenakshi-dhanani for sharing your thoughts. @ramitsawhney27, can I also please have your thoughts on this? If we decide to do the logic at the backend, before moving to creating View and Update Programs on frontend, I'll refactor the relevant date related fields on any endpoints that are currently using the unix dates to accept the human readable format (perhaps RFC 2822: Thursday, 31-Dec-20 00:00:00 UTC). But the database will be kept in double precision format.

2020-08-22 14:05 UTC, meenakshi-dhanani commented
We use context when there is some global state that we want a lot of components to use, eg. login, logout, etc.

If a user is a representative, is this state required across the application?
Also, a cookie has data that will disappear if the client clears it. This gives a wrong picture. And cookie data can be modified to get access to my organization pages. There can also be cases, when the the backend says something and the cookie reflects differently.

In case a user is a representative, should one call suffice? Is it really necessary to keep it in context?
And definitely this information should not be part of a cookie

2020-08-22 14:10 UTC, meenakshi-dhanani commented
What we can do is shift the My Organization as a separate submenu inside My Space. We can simply show that irrespective of whether a user is a representative or no, if a user is not representative, let that page not show up. If the user is a representative then let's show the form. 
Also, let's get the information whether a user is representative or no from an api call. I see the usage of is_representative in this component only so let's not keep it as part of the AuthContext also because it has no relation to authentication

2020-08-22 14:21 UTC, mtreacy002 commented
```quote
 If a user is a representative, is this state required across the application?
```
@meenakshi-dhanani . is_organization_representative in the frontend is used to set thee Navbar which is re-rendered on each pages user go to. So, in this case, I would say, yes, the value needs to be placed in Context.

```quote
In case a user is a representative, should one call suffice? Is it really necessary to keep it in context?
```

as per the answer above, it's needed on the Navbar

```quote
And definitely this information should not be part of a cookie
```
Yeah, I think keeping it in AuthContext will suffice. Do you agree?

2020-08-22 14:24 UTC, mtreacy002 commented
> What we can do is shift the My Organization as a separate submenu inside My Space. We can simply show that irrespective of whether a user is a representative or no, if a user is not representative, let that page not show up. If the user is a representative then let's show the form.
> Also, let's get the information whether a user is representative or no from an api call. I see the usage of is_representative in this component only so let's not keep it as part of the AuthContext also because it has no relation to authentication

On this point, @meenakshi-dhanani , since the Navbar menu gets re-rendered every time user go to different pages, the submenu My Organisation will be checked against the is_organization_rep every time a new page is rendered. If not in AuthContext, how would you suggest we keep the value of this attribute?

2020-08-22 14:55 UTC, meenakshi-dhanani commented
> > What we can do is shift the My Organization as a separate submenu inside My Space. We can simply show that irrespective of whether a user is a representative or no, if a user is not representative, let that page not show up. If the user is a representative then let's show the form.
> > Also, let's get the information whether a user is representative or no from an api call. I see the usage of is_representative in this component only so let's not keep it as part of the AuthContext also because it has no relation to authentication
> 
> On this point, @meenakshi-dhanani , since the Navbar menu gets re-rendered every time user go to different pages, the submenu My Organisation will be checked against the is_organization_rep every time a new page is rendered. If not in AuthContext, how would you suggest we keep the value of this attribute?

What I'm suggesting is this need not be in the navbar for now. You can keep my organization inside my space. Similar to how you handle personal information. If a user doesn't have any information you say that the user is not a representative, if the user wants to be then the user must check the box in additional details. If the user is then show the form. Also, the fact that a user is representative can be received via an API call that could be made. 

The responsibility of the AuthContext is not to keep other fields, it's just the access token that is very tightly coupled with authentication. So definitely not inside AuthContext. 


You could do an api call that includes in it's response - is_representative details
Maybe the additional-details call returns that flag right? make that call and fetch from there?


Also the responsibility and expected payload of a login API is not to return the is_representative_flag. So in both ways it's not right

2020-08-22 14:59 UTC, mtreacy002 commented
> > > What we can do is shift the My Organization as a separate submenu inside My Space. We can simply show that irrespective of whether a user is a representative or no, if a user is not representative, let that page not show up. If the user is a representative then let's show the form.
> > > Also, let's get the information whether a user is representative or no from an api call. I see the usage of is_representative in this component only so let's not keep it as part of the AuthContext also because it has no relation to authentication
> > 
> > 
> > On this point, @meenakshi-dhanani , since the Navbar menu gets re-rendered every time user go to different pages, the submenu My Organisation will be checked against the is_organization_rep every time a new page is rendered. If not in AuthContext, how would you suggest we keep the value of this attribute?
> 
> What I'm suggesting is this need not be in the navbar for now. You can keep my organization inside my space. Similar to how you handle personal information. If a user doesn't have any information you say that the user is not a representative, if the user wants to be then the user must check the box in additional details. If the user is then show the form. Also, the fact that a user is representative can be received via an API call that could be made.
> 
> The responsibility of the AuthContext is not to keep other fields, it's just the access token that is very tightly coupled with authentication. So definitely not inside AuthContext.
> 
> You could do an api call that includes in it's response - is_representative details
> Maybe the additional-details call returns that flag right? make that call and fetch from there?
> 
> Also the responsibility and expected payload of a login API is not to return the is_representative_flag. So in both ways it's not right

Ok, Can you please open a PR for the refactoring? both on backend and frontend? I'll do it post GSoC.

2020-08-23 05:00 UTC, mtreacy002 commented
@meenakshi-dhanani Thanks for your help sorting out the Navbar. I've merged the PR you raised to this one. Can you please re-review? Thanks. cc @anitab-org/bridgeintech-maintainers

2020-08-23 05:19 UTC, meenakshi-dhanani commented on src/AuthContext.js
> +    Cookies.remove("is_organization_representative");
this line should not be there

2020-08-23 05:25 UTC, mtreacy002 commented on src/AuthContext.js
> +    Cookies.remove("is_organization_representative");
Done. It's now removed

2020-08-23 05:25 UTC, meenakshi-dhanani commented
> @meenakshi-dhanani Thanks for your help sorting out the Navbar. I've merged the PR you raised to this one. Can you please re-review? Thanks. cc @anitab-org/bridgeintech-maintainers

We just need to remove that line in AuthContext, and I will approve

2020-08-23 05:27 UTC, mtreacy002 commented
> > @meenakshi-dhanani Thanks for your help sorting out the Navbar. I've merged the PR you raised to this one. Can you please re-review? Thanks. cc @anitab-org/bridgeintech-maintainers
> 
> We just need to remove that line in AuthContext, and I will approve

Done that, @meenakshi-dhanani .

2020-08-23 05:56 UTC, meenakshi-dhanani submitted a review, later dismissed

2020-08-23 06:16 UTC, meenakshi-dhanani approved these changes

2020-08-23 06:17 UTC, meenakshi-dhanani commented
![EditOrganization](https://user-images.githubusercontent.com/14279061/90972404-56793480-e536-11ea-98ba-99dd5d8c3c9e.gif)

2020-08-23 07:55 UTC, meenakshi-dhanani commented
@ramitsawhney27 all changes LGTM, can you approve if it looks fine?

2020-08-23 15:06 UTC, meenakshi-dhanani commented
@isabelcosta I have attached the .gif above that shows the following:
- Displays organization not declared for a user, who is not an organization representative
- Edit organization for a user that represents an organization
Can you check?

2020-08-23 18:52 UTC, meenakshi-dhanani requested changes
I took the latest pull and ran again, I had missed the following scenario:

If a organization does not exist for a user, allow the user to create the organization when Organization profile is clicked under my organization. This is breaking, needs to be fixed.

2020-08-23 22:31 UTC, isabelcosta commented
@meenakshi-dhanani can you explain the bug a little bit more, I didn't understand your sentence 😕

2020-08-23 23:32 UTC, mtreacy002 commented
@meenakshi-dhanani , I've fixed the initial page rendering so user can fill in the form to create organization if they haven't create one.

2020-08-24 07:38 UTC, meenakshi-dhanani commented
@isabelcosta The bug I reported, was about a user, that says that he/she/they are representing an organization, but have no organization created. The expected behavior would be to see a create organization form for them. Maya has pushed the fix for that now. So that is working with the fix.

2020-08-24 07:38 UTC, meenakshi-dhanani approved these changes

2020-08-25 13:39 UTC, foongminwong approved these changes
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _View/Create and Update organization Profile_  
    _Screenshot/gif/url_:  

     ![test-bit-web-pr-69-create-organization-profile](https://user-images.githubusercontent.com/23441795/91181419-79187280-e71b-11ea-81a8-b9bc437e8bff.gif)


    _Expected Result_:  As a user, i should be able to view, create, update org profile as an org rep.
    _Actual Result_: Same as expected

3. OS Version: Windows 10

2020-08-25 14:54 UTC, merged