feat(register): added password confirmation field
anitab-org/bridge-in-tech-web pull request #89
Opened 2020-09-03 10:07 UTC by ruppysuppy

### Description

Added password confirmation field in Regitration form

Fixes #85 

### Type of Change:

- User Interface

### How Has This Been Tested?

UI Visually tested for the confirm password field.
![1](https://user-images.githubusercontent.com/44058757/92101787-3e899680-edfb-11ea-8808-c30d0e811279.PNG)
![2](https://user-images.githubusercontent.com/44058757/92101824-519c6680-edfb-11ea-95d6-a0eb4695faec.PNG)
![3](https://user-images.githubusercontent.com/44058757/92101836-552fed80-edfb-11ea-8290-2ebf082be43d.PNG)

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

2020-09-03 10:12 UTC, ruppysuppy commented
The build is [failing](https://travis-ci.com/github/anitab-org/bridge-in-tech-web/builds/182573315#L247), but I haven't changed that [part](https://github.com/anitab-org/bridge-in-tech-web/pull/89/commits/69a711fba00aad6df0db061bcdf60c1d14f2166b). Could you give me some suggestions @mtreacy002?

2020-09-03 11:35 UTC, mtreacy002 commented
@ruppysuppy. I didn't see you put a request to work on an this issue. As per the [Contributing Guideeline](https://github.com/anitab-org/bridge-in-tech-web/blob/develop/.github/CONTRIBUTING.md#general-guidelines) within AnitaB.Org Open Source, you should claim an issue first and wait till a maintainer assign you to the issue. This is to prevent developers working on the same issue. It also helps keeping things in order (in case more than one developer claiming the issue, the first one who put the request is the one who normally gets to work on it). Can you imagine if you already started working on the issue before claiming it, then before you push the code someone else claim the issue and gets assign to work on it? It'll be a waste of your time, don't you think? So, for next time, I advise you to claim the issue first before start working on it. For now, can you put a request on the issue so I can assign you?

2020-09-03 12:10 UTC, ruppysuppy commented
I would like to work on this issue

2020-09-03 12:15 UTC, mtreacy002 commented
> I would like to work on this issue

Can you post this on the issue itself, @ruppysuppy ?

2020-09-03 12:17 UTC, ruppysuppy commented
Sorry 😅

2020-09-03 14:12 UTC, ruppysuppy commented
Could you review it now @mtreacy002?

2020-09-04 01:08 UTC, mtreacy002 requested changes
@ruppysuppy. Great job for pushing the PR pretty quickly. Can you check my feedback below? Also, it is recommended that contributors also write the test cases to test the code they are proposing. Will you be able to do this (adding another test when confirmPassword field doesn't match the password field then an error message should be shown). It's ok if you're not feeling comfortable on this, we can open another issue for another contributor to write the test cases. Let me know what you think. 😉

2020-09-04 01:08 UTC, mtreacy002 commented on src/register/Register.jsx
> +            delete payload.confirmPassword
It would be best to filter out the `confirmPassword` instead of adding it to the payload then delete it after. You could just add an if condition that checks if the key is confirmPassword then simply go to the next key. You can check the similar method used in PersonalDetails.jsx. Does this make sense?

2020-09-04 02:34 UTC, ruppysuppy commented
Please open another issue for it, I'm not good at writing tests, but I sure will give it a try

2020-09-04 03:19 UTC, mtreacy002 commented
> Please open another issue for it, I'm not good at writing tests, but I sure will give it a try

No worries. Will open another issue then. You've done great job with this one. Just need to address my feedback [here](https://github.com/anitab-org/bridge-in-tech-web/pull/89#discussion_r483328294) then I'll approve. Thank you for your contribution 👍.

2020-09-04 03:25 UTC, ruppysuppy commented
I have addressed the problem. Could you review it?

2020-09-04 03:44 UTC, mtreacy002 approved these changes, later dismissed
Good job, @ruppysuppy. LGTM now. 👍

2020-09-04 03:45 UTC, mtreacy002 commented
@anitab-org/bridgeintech-maintainers , can someone please also review this? Thanks

2020-09-04 05:52 UTC, ruppysuppy commented
@mtreacy002 I have prepared the tests for the confirm password, I'll open a new pull request (and issue too) for it after this one is merged as that PR (test) will be dependent on this PR

2020-09-04 14:42 UTC, ruppysuppy commented
@mtreacy002 what did you assign me to? Btw, github's saying @anitab-org/bridgeintech-maintainers is not available

2020-09-05 10:11 UTC, mtreacy002 approved these changes
I have approved this PR, @anitab-org/bridgeintech-maintainers and @ruppysuppy

2020-09-06 07:53 UTC, foongminwong approved these changes
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _Password confirmation field_  
      _Screenshot/gif/url_:  

        ![test-bit-web-pr-89](https://user-images.githubusercontent.com/23441795/92321025-0aabac80-f059-11ea-8581-8eea0ab539b5.gif)

      _Expected Result_:  As a user, the website should have a password confirmation field on registration page.
      _Actual Result_: Same as expected

3. OS Version: Windows 10

@ruppysuppy 🎉

2020-09-06 07:55 UTC, merged