Test: Add tests for validations on personal detail fields
anitab-org/bridge-in-tech-web pull request #95
Opened 2020-09-11 07:21 UTC by Aaishpra

### Description

Solves the following

- Assert if validation check pops up for username - "Must be between 5-25 characters long. Can only contain alphabets, numbers and underscore _"

- Asset if validation check pops up for name field - "Must be between 2-30 characters long. Can only contain alphabets, whitespace, and dash -"

- Test to ensure the required fields are not empty for username and name.

Fixes #64

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

All the tests are passing in VS code terminal

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2020-09-11 07:26 UTC, Aaishpra commented
@mtreacy002 please review this.

2020-09-12 01:33 UTC, mtreacy002 submitted a review, later dismissed
@Aaishpra , LGTM. Well done for completing the task in such a short time, 👍. Thank you for your contribution to the project.

2020-09-12 01:35 UTC, mtreacy002 commented
@anitab-org/bridgeintech-maintainers or @anitab-org/coding-team . Can someone also please help reviewing this PR? Thanks in advance.

2020-09-13 06:08 UTC, Kajol-Kumari requested changes
@Aaishpra Minor changes required. Rest Looks good to me :+1:

2020-09-13 06:08 UTC, Kajol-Kumari commented on src/tests/PersonalDetails.test.js
> +
Please remove the extra spaces and just keep single line space where-ever required.

2020-09-13 06:37 UTC, Aaishpra commented
@mtreacy002 @Kajol-Kumari  Please have a look now.

2020-09-14 13:17 UTC, mtreacy002 approved these changes
This one too, LGTM, @Aaishpra 👍 . Thanks again for the fix.

2020-09-15 18:35 UTC, Kajol-Kumari approved these changes
@Aaishpra thanks for making the requested changes. This looks good to me now :)

2020-09-15 18:47 UTC, keshakaneria approved these changes
Squash the commits @Aaishpra and you are good to go! 🎉

2020-09-15 22:44 UTC, mtreacy002 commented
@Kajol-Kumari and @keshakaneria, thanks for your review. Although, they are not yet counted as approval. Can you please tick the `Approve` box to officially approve the PR? Other than `Approve`, the review doesn't count as being approved (see the second image)
<img width="602" alt="Screen Shot 2020-09-16 at 8 40 21 am" src="https://user-images.githubusercontent.com/29667122/93272379-b17e0e80-f7f8-11ea-9144-c67373588b46.png">
<img width="639" alt="Screen Shot 2020-09-16 at 8 41 09 am" src="https://user-images.githubusercontent.com/29667122/93272386-b5119580-f7f8-11ea-9f78-1eeb21dd5b41.png">

2020-09-15 23:06 UTC, merged

2020-09-16 07:33 UTC, keshakaneria commented
@mtreacy002 I suppose its merged now so no need to do this. Sorry for the late response before merging but will take care next time to check that option too :)

2020-09-16 07:36 UTC, mtreacy002 commented
> @mtreacy002 I suppose its merged now so no need to do this. Sorry for the late response before merging but will take care next time to check that option too :)

No worries, @keshakaneria, it's just a little hiccup that could happen to anyone. Thanks anyway for your giving time to give a review 😉

2020-09-16 07:38 UTC, mtreacy002 commented
While you're here, can you please give approval on PR #93? Just want to confirm that someone who is not a maintainer can approve the PR. Thanks heaps for helping.

2020-09-16 07:40 UTC, mtreacy002 commented
Sorry, cancel that. It's also been approved and merged (PR #93) 😁