Added link to AnitaB.Org in contact menu
anitab-org/bridge-in-tech-web pull request #99
Opened 2020-09-16 15:54 UTC by Harshita-Kanal

### Description

Fixes #98 

### Type of Change:

- Code
- Quality Assurance
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Tested Locally

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-09-17 12:50 UTC, gaurivn submitted a review, later dismissed
Good work :tada: thank you

2020-09-18 00:31 UTC, mtreacy002 requested changes
@Harshita-Kanal , can you please make the link open to a new tab? This is so if the user still have our website open in a separate tab, they are more likely continue exploring BridgeInTech web and not distracted to explore AnitaB.Org site (so here we are aiming for higher retention 😉)

2020-09-18 05:50 UTC, Kajol-Kumari commented on src/Navigation.js
> +                                        <Nav.Link href="https://anitab.org/contact/">Contact</Nav.Link>
Please use something like `target="_blank"` attribute here so that we don't loose the opened page of the site.

2020-09-18 07:35 UTC, Harshita-Kanal commented
I made the changes, I don't know why is it showing the dismissed review comment, I just pushed a commit. Thanks.

2020-09-18 08:20 UTC, mtreacy002 commented
> I made the changes, I don't know why is it showing the dismissed review comment, I just pushed a commit. Thanks.

This is normal, @Harshita-Kanal , since you've pushed a new update, the approval given prior to the new push automatically got dismissed. You'll see this often, so, don't be alarmed 😉.

2020-09-18 08:48 UTC, mtreacy002 approved these changes
This LGTM, @Harshita-Kanal. Great job on your First-Timers-Only issue. 🎉🎉
Thank you again for contributing to the project. 👍
Don't forget to join the [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) zulip channel to keep up with the project progress and discussions 😉

2020-09-18 09:02 UTC, mtreacy002 commented
@Harshita-Kanal ,  can you please add `Feat: ...` (aka Feature) in front of the title of this PR? Just so when we browse through thee list of PR we know what type of PR this is. 
Also just few little things I need to mention for you to apply in the next contribution. 
* Please make sure you follow the [Commit Message Style Guide](https://github.com/anitab-org/bridge-in-tech-web/wiki/Commit-Message-Style-Guide) that is mentioned in the [Getting Started wiki page](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started) under section `Start Working` so to maintain consistency across the repositories.

2020-09-18 11:09 UTC, Harshita-Kanal commented
Sure, thank you

2020-09-19 07:49 UTC, Kajol-Kumari approved these changes
LGTM :+1:  
Thank you for your contribution @Harshita-Kanal  :)

2020-09-21 07:42 UTC, merged